# 01/01/2021 00:01:34
trigger:
  branches:
    include:
    - '*'

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

parameters:
- name: images
  type: object
  default: ["ntutselab/stable-baselines-gpu:latest", "ntutselab/stable-baselines-gpu:v2.10.1-MPI", "ntutselab/stable-baselines-gpu:v2.10.1", "ntutselab/stable-baselines-gpu:v2.9.3", "ntutselab/stable-baselines-gpu:v2.9.2-MPI", "ntutselab/stable-baselines-gpu:v2.9.2", "ntutselab/stable-baselines-gpu:v2.9.0-MPI", "ntutselab/stable-baselines-gpu:v2.9.0", "ntutselab/vocal-detection:latest", "ntutselab/vocal-detection:v2.0.2", "ntutselab/vocal-detection:v2.0.1", "ntutselab/vocal-detection:v2.0.0", "ntutselab/vocal-detection:v1.0.0", "ntutselab/keystonejs:latest", "ntutselab/keystonejs:v1.1", "ntutselab/keystonejs:v1.0", "ntutselab/stable-baselines-cpu:latest", "ntutselab/stable-baselines-cpu:v2.9.3", "ntutselab/stable-baselines-cpu:v2.10.1-MPI", "ntutselab/stable-baselines-cpu:v2.10.1", "ntutselab/stable-baselines-cpu:v2.9.3-MPI", "ntutselab/stable-baselines-cpu:v2.9.2-MPI", "ntutselab/stable-baselines-cpu:v2.9.2", "ntutselab/stable-baselines-cpu:v2.9.1-MPI", "ntutselab/stable-baselines-cpu:v2.9.1", "ntutselab/stable-baselines-cpu:v2.9.0-MPI", "ntutselab/stable-baselines-cpu:v2.9.0", "ntutselab/libsystem:latest", "ntutselab/microsoft-graph-bot:0.0.40.0", "ntutselab/microsoft-graph-bot:1.1.0.0", "ntutselab/microsoft-graph-bot:1.0.1.0", "ntutselab/microsoft-graph-bot:1.1.1.0", "ntutselab/microsoft-graph-bot:1.0.0.0", "ntutselab/microsoft-graph-bot:latest", "ntutselab/microsoft-graph-bot:1.1.3.0", "ntutselab/microsoft-graph-bot:1.1.2.0", "ntutselab/timeoff_management_with_coverage:latest", "ntutselab/timeoff_management_for_learning:latest", "ntutselab/nodebb_with_coverage:latest", "ntutselab/mongo:latest", "ntutselab/tf_image:latest", "ntutselab/tf_image:v1.15.2", "ntutselab/tf_image:v2.1", "ntutselab/fintech:latest", "ntutselab/fintech:1.1", "ntutselab/fintech:1.0", "ntutselab/keystonejs_with_coverage:latest", "ntutselab/tf-faster-rcnn-deps:latest", "ntutselab/tf-faster-rcnn-deps:v1.0.0" ]

jobs:
- ${{ each image in parameters.images }}:
  - job:
    displayName: '${{ image }}'
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: DockerHub
    - script: 'docker pull ${{ image }}'
      displayName: 'docker pull ${{ image }}'
    - task: Docker@2
      displayName: Logout of Docker Hub
      inputs:
        command: logout
        containerRegistry: DockerHub
